export default [
  {
    host: "localhost",
    IP: "127.0.0.1",
    port: "69",
    port_name: "TFTP",
    password: "6969",
  },
  {
    host: "www.microsoft.com",
    IP: "20.112.250.133",
    port: "22",
    port_name: "SSH",
    password: "billion_gates",
  },
  {
    host: "www.telstra.com.au",
    IP: "13.227.8.61",
    port: "445",
    port_name: "SMB",
    password: "aussie_tel",
  },
  {
    host: "www.bankwest.com.au",
    IP: "18.66.161.107",
    port: "23",
    port_name: "Telnet",
    password: "bank2west",
  },
  {
    host: "www.icq.com",
    IP: "5.61.236.229",
    port: "53",
    port_name: "DNS",
    password: "userKill",
  },
  {
    host: "www.nystockexchange.com",
    IP: "45.56.79.23",
    port: "80",
    port_name: "HTTP",
    password: "yankees",
  },
  {
    host: "www.tafe.wa.edu", // IRL: www.tafeinternational.wa.edu.au
    IP: "151.101.130.191",
    port: "25",
    port_name: "SMTP",
    password: "ginger",
  },
  {
    host: "www.cnet.com",
    IP: "10.10.34.35",
    port: "137",
    port_name: "NetBIOS",
    password: "fakenews404",
  },
  {
    host: "www.trendmicro.com",
    IP: "104.80.211.113",
    port: "1433",
    port_name: "SQL",
    password: "safepass",
  },
  {
    host: "www.worldbank.org",
    IP: "13.227.8.55:",
    port: "3389",
    port_name: "Remote Desktop",
    password: "wealth.dlc",
  },
  {
    host: "www.apple.com",
    IP: "2.18.160.212",
    port: "443",
    port_name: "HTTPS",
    password: "banana",
  },
  {
    host: "www.ebay.com",
    IP: "23.213.165.89",
    port: "8080",
    port_name: "HTTPS",
    password: "ecursive",
  },
];
